### ISSUE TITLE
关于翻译导致部分功能丢失

### ISSUE THREAD

**Issue by hongmengshikong** [zryyyy/Cisco-Packet-Tracer-Chinese#3]
如图所示，使用该翻译前
![QQ截图20240308212543](https://github.com/zryyyy/Cisco-Packet-Tracer-Chinese/assets/134291656/e8238a51-e5cf-4898-8274-922726a53236)

使用该翻译后
![QQ截图20240308212423](https://github.com/zryyyy/Cisco-Packet-Tracer-Chinese/assets/134291656/527d0018-0882-40a5-b0dc-0bcdb928ba59)

**Comment by hongmengshikong** [comment]
个人认为可以结合湖科大教书匠的汉化，在此基础上进行进一步的汉化工作

**Comment by zryyyy** [comment]
- #1 翻译的问题是因为这个文件大部分内容都是机翻的，做不到每一个翻译都完全准确，我能修改的也只是我之前在使用时碰到的问题。这个 issue 的翻译问题我会在之后修改
- #2 关于这个问题我没有更换过思科的默认字体，所以很难定位问题在哪里。但是我查了一下 Courier New 这个字体对于中文的支持并不好
- #3 这个窗口我没有用过，我认为可能也跟字体对中文的支持程度有关
- 如果 issue 都是关于翻译问题的话，尽量还是都提到同一个 issue 里吧。在我能力范围内可以解决的问题我都会尽量解决的，但是我现在用这软件也不是很多了，如果你可以提 pr 帮我修复一些问题那就更好了
