### ISSUE TITLE
鼠标悬停在图标时的问题

### ISSUE THREAD

**Issue by sunxiaochuan2586** [zryyyy/Cisco-Packet-Tracer-Chinese#6]
![image](https://github.com/user-attachments/assets/12e11069-7da9-40a8-b3a6-5563a12a47df)
![image](https://github.com/user-attachments/assets/bd337d0a-8c3e-4d2e-a495-29859047d4b5)
如图所示

**Comment by sunxiaochuan2586** [comment]
不知道是我的问题还是文件的问题:) 望解答

**Comment by zryyyy** [comment]
我的版本也是 8.2.2 没出现你说的问题
修改 pt 的字体可能会出现问题，但是看你的截图好像也不像改过
![image](https://github.com/user-attachments/assets/261f7df9-1a5b-4e3a-b4f7-657b8d5e6b82)
你可以发一下你的系统的详细配置吗

**Comment by zryyyy** [comment]
你好，这个issue你一直没回我先关了哈，如果你后面想起来了可以重新把这个issue打开

**Comment by sunxiaochuan2586** [comment]
![f923f562c33501c355359d6d90bdc6e](https://github.com/user-attachments/assets/2fff5b79-343b-4b8b-a9cb-94961bc5dd47)
抱歉才看到，这个是我的电脑配置

**Comment by zryyyy** [comment]
你鼠标在其他图标上悬浮也会显示黑色吗？还是说就这个图标会显示黑色

**Comment by sunxiaochuan2586** [comment]
> 你鼠标在其他图标上悬浮也会显示黑色吗？还是说就这个图标会显示黑色

都会黑，我现在在另外一台电脑上，是正常的:)

**Comment by sunxiaochuan2586** [comment]
> > 你鼠标在其他图标上悬浮也会显示黑色吗？还是说就这个图标会显示黑色
> 
> 都会黑，我现在在另外一台电脑上，是正常的:)

![image](https://github.com/user-attachments/assets/44d68ec7-3b9c-4934-9100-81c6e2a1ad91)
在学校的电脑室里头，这是它的配置

**Comment by zryyyy** [comment]
那可能是那台电脑有点问题？可能重装一下pt会解决吧

**Comment by sunxiaochuan2586** [comment]
> 那可能是那台电脑有点问题？可能重装一下pt会解决吧

下午我回去试试

**Comment by sunxiaochuan2586** [comment]
我好像复刻成功了，就是把字体大小调大的时候，就会出现这样的问题

**Comment by zryyyy** [comment]
> 我好像复刻成功了，就是把字体大小调大的时候，就会出现这样的问题

噢噢，那这个应该是软件的问题了
